<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B2426KB" ignored="2" name="Test(failed)" tests="3" failures="1" timestamp="2021-01-13T13:08:04 IST" time="0.036" errors="0">
  <testcase name="test2" time="0.007" classname="com.qa.testNG.Runner">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.qa.testNG.Runner">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.qa.testNG.Runner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.testNG.Runner.test2(Runner.java:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.qa.testNG.Runner">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="com.qa.testNG.Runner">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
